### ISSUE TITLE
Can't get it to connect on a Raspberry Pi 2

### ISSUE THREAD

**Issue by skpang** [dschanoeh/Kayak#20]
Has anyone got Kayak working on the Raspberry Pi 2?

I've got socket can up as can0 and when I try to connect as socket//can0@192.168.1.194:29536
It won't connect. Is the syntax correct?

**Comment by dschanoeh** [comment]
Hi @skpang, just to make sure: Did you also install the socketcand (https://github.com/dschanoeh/socketcand) on the Raspberry? This is a necessary component between the SocketCAN device and Kayak. When that's running on the same machine, you should also see the enabled buses show up in auto discovery in Kayak without having to manually enter the URL...
If you have all that running and still want to use the URL, you are missing a colon after the socket "socket://"

**Comment by skpang** [comment]
Hi @dschanoeh, thanks for the reply. No didn't have socketcand installed. I'm trying now to install socketcand. The Pi didn't have autoconf so I install it by sudo apt-get install autoconf then run
$autoconf 
$./configure
$make clean
$make

but I'm getting these errors:

pi@raspberrypi ~/socketcand $ autoconf
pi@raspberrypi ~/socketcand $ ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for config_init in -lconfig... no
configure: error: in `/home/pi/socketcand':
configure: error: config test failed (--without-config to disable)
See `config.log' for more details
pi@raspberrypi ~/socketcand $ make clean
make: *** No rule to make target 'clean'.  Stop.
pi@raspberrypi ~/socketcand $ make
make: *** No targets specified and no makefile found.  Stop.
pi@raspberrypi ~/socketcand $ ^C

What can I do to fix this error?
Attached is the config.log

[config.log.zip](https://github.com/dschanoeh/Kayak/files/115793/config.log.zip)

**Comment by dschanoeh** [comment]
Did you install the libconfig development package (should be called libconfig-dev)?

**Comment by skpang** [comment]
Hi @dschanoeh, I have installed the libconfig and autoconf and managed to get Kayak to work on the Raspberry Pi2.
I've written up the extra steps required on my blog http://skpang.co.uk/blog/archives/1242

Thank you for writing Kayak.

**Comment by dschanoeh** [comment]
Cool, thank you for writing down those steps!

**Comment by dav2dg** [comment]
I followed the directions above (and at skpang). I get an error in the .configure step.

Any advice please for the following error:

`checking sys/time.h usability... yes
checking sys/time.h presence... ./configure: line 1574: conftest.c: Protocol error
sed: can't read conftest.c: Protocol error
rm: cannot remove 'conftest.c': Protocol error
no
configure: WARNING: sys/time.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: sys/time.h: proceeding with the compiler's result
checking for sys/time.h... yes
checking syslog.h usability... ./configure: line 1557: conftest.c: Protocol error
./configure: line 1419: conftest.err: Protocol error
sed: can't read conftest.c: Protocol error
rm: cannot remove 'conftest.err': Protocol error
rm: cannot remove 'conftest.c': Protocol error
no
checking syslog.h presence... ./configure: line 1574: conftest.c: Protocol error
./configure: line 1503: conftest.err: Protocol error
sed: can't read conftest.c: Protocol error
rm: cannot remove 'conftest.err': Protocol error
rm: cannot remove 'conftest.c': Protocol error
no
checking for syslog.h... no
configure: error: not all required headers are present
rm: cannot remove 'conftest.c': Protocol error
rm: cannot remove 'conftest.err': Protocol error
`
