### ISSUE TITLE
Kajak compile error

### ISSUE THREAD

**Issue by matricola130** [dschanoeh/Kayak#31]
This is the error.  =/

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project Kayak-mapview: Compilation failure

[ERROR] /home/kali130/Kayak/Kayak-mapview/target/generated-sources/annotations/com/github/kayak/mapview/Bundle.java:[3,18] cannot find symbol
[ERROR]   symbol:   class Generated
[ERROR]   location: package javax.annotation
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :Kayak-mapview

**Comment by dschanoeh** [comment]
ee17bf7c6360395f43e6d5d54cf91d6856f25ff3 fixed this.
